apiVersion: apps.danielhu.cn/v1
kind: Application
metadata:
  name: nginx-sample
  namespace: default
spec:
  deployment:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80