apiVersion: apps.danielhu.cn/v1
kind: Application
metadata:
  name: nginx-sample-2
  namespace: default
  labels:
    app: nginx-2
spec:
  deployment:
    replicas: 1
    selector:
      matchLabels:
        app: nginx-2
    template:
      metadata:
        labels:
          app: nginx-2
      spec:
        containers:
        - name: nginx-2
          image: nginx:1.14.2
          ports:
          - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080